### ISSUE TITLE
Fatal error when trying to "Synchronise" from the plugin administration page

### ISSUE THREAD

**Issue by tanty** [Piwigo/piwigo-videojs#204]
Go to VideoJS' admin UI. Select the "Synchronise" tab.

Leave the default options, including the "perform a simulation only (nothing will be changed in the database)" one.

Click "Submit".

I get the following Fatal error:

```
Warning: Undefined array key "vjs_sync" in /config/www/plugins/piwigo-videojs/admin/admin_sync.php on line 78

Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in /config/www/plugins/piwigo-videojs/admin/admin_sync.php:78 Stack trace: #0 /config/www/plugins/piwigo-videojs/admin/admin_sync.php(78): array_merge() #1 /config/www/plugins/piwigo-videojs/admin/admin.php(68): include_once('...') #2 /app/www/public/admin/plugin.php(53): include_once('...') #3 /app/www/public/admin.php(345): include('...') #4 {main} thrown in /config/www/plugins/piwigo-videojs/admin/admin_sync.php on line 78
```

This is with piwigo 13.6.0 from [linuxserver.io](https://docs.linuxserver.io/images/docker-piwigo)

Environment:
```
Piwigo 13.6.0
Installed on 30 January 2019, 4 years 2 months 3 days ago
Operating system: Linux
PHP: 8.0.28
MySQL: 10.6.12-MariaDB-log
Graphics Library: ImageMagick 7.1.0-50
Cache size 10652.34 Mo
VideoJS plugin 2.9.b
```

**Comment by ember1205** [comment]
Same exact issue here. Occurring on a hosted Debian server where I'm trying to get the mediainfo and ffmpeg tools installed because they aren't provided by the hosting company and I can't do anything because this error needs to be fixed -first-.

**Comment by EddyLB** [comment]
Have you tried to install a binary of [ExifTool](https://exiftool.org/install.html) and [ffmpeg](https://ffmpeg.org/download.html) and configure your Piwigo as suggested in the [wiki page](https://github.com/Piwigo/Piwigo-Mobile/wiki/Configure-Piwigo-for-Uploading-Videos) of the Piwigo iOS app?

**Comment by ember1205** [comment]
What specific files are to be edited via that plugin? That's one thing that I have been struggling with across many items is that it isn't specified which file to edit.

Would that configuration actually have any effect at all given that the files in my case were uploaded by FileZilla and I am trying to run the Synchronize process? This is the process by which I loaded all of my photos and the native sync process in Piwigo imported all of them fine.

Also, I have a statically-linked version of ffmpeg on my host, but there are zero details in any install docs that I can find that tell me whether those files can be placed at the root of my home directory or if they must be placed within the folder that holds the web content. And again, I can't find details for which file to edit for videojs to update the location of these files correctly - one area says to use LocalFiles Editor but doesn't tell which file, another area says to edit the admin_photo.php file but that doesn't seem to get read by the plugin.

The other big red flag here is that the bottom of the Settings page for the plugin has errors at the Resolution settings that I have no way to understand because it appears that the error and the page text are blended together somehow.

**Comment by EddyLB** [comment]
If you copy/paste the lines provided in [this wiki](https://github.com/Piwigo/Piwigo-Mobile/wiki/Configure-Piwigo-for-Uploading-Videos) in the Local Config tab of the [LocalFiles Editor](https://piwigo.org/ext/extension_view.php?eid=144) plugin and then change the paths of the binaries given as example, VideoJS will be able to call ExifTool and ffmpeg.

As for finding synced videos, I cannot help you because I do not import videos this way. Sorry.

**Comment by ember1205** [comment]
Editing the directory / path location seems to do nothing, though. Opening the Settings for the videojs plugin and moving to the Synchronize tab still shows errors for all of the supporting tools even though the paths have been updated correctly. There are multiple "array key" errors in different areas of the plugin as well seeming to imply that the plugin isn't going to actually work whether it's running in the background as videos are being uploaded or if it's being run manually through the Admin interface.

exiftool is explicitly called out as not being necessary, so I haven't yet tried adding that one to the server... mediainfo, ffprobe, and ffmpeg are all present though.

**Comment by EddyLB** [comment]
Hum… strange. I use Piwigo 13.6.0 and the VideoJS plugin 2.9.b downloaded from [here](https://github.com/Piwigo/piwigo-videojs) w/o issue.
Have you looked at the other issues related to "array key" errors?

**Comment by ember1205** [comment]
I installed the plugin through Piwigo. I read elsewhere that doing a git pull from here may help with some issues, but also seemed like it might cause others so I hadn't gone down the path of trying that as an option.

When you say "looked at the other issues", what do you mean? In what way?

**Comment by tanty** [comment]
Please, move this discussion somewhere else. This bug is not about problems with the installation of the "Program Dependencies". In my report I do have those tools properly installed, they appear with a green check mark in the Settings -> Synchronise tab and, indeed, synchronization works perfectly on individual videos.

Yet, this failure happens when following the described steps.

**Comment by ember1205** [comment]
You can consider this conversation dead, then. The goal is solve the underlying problem and that doesn't always happen by insisting that only a very specific subset of issues are discussed.

**Comment by EddyLB** [comment]
Should be fixed with https://github.com/Piwigo/piwigo-videojs/pull/229
