### ISSUE TITLE
binary path

### ISSUE THREAD

**Issue by Emir-Heinz** [Piwigo/piwigo-videojs#41]
How must look a binary path. Give me please a sample.
Program Dependencies 
•   Mediainfo binary path 
'MediaInfo' must be install to allow video metadata parsing. 
•   FFmpeg binary path 
'FFmpeg' must be install to allow video thumbnail and poster generation.

**Comment by Amroaez** [comment]
Hi @xbgmsharp and all community,

i'm new to the forum, can i  ask you a question if you can help me to fix an error that i get when I apply options that use FFMPEG.
even if the plugin confirms the creation of the Thumbnails, and the POSTERS but also the mediainfo.
I installed everything following the documentation step by step and various bug fixes but I can't solve the problem.

The configuration is PWG 11 installed on ReadyNas as an App.

from ssh (root) I have installed mediainfo, ffmpeg and the various libraries as per documentation. I have configured as suggested by you in other posts the PATH of ffmpeg, mediainfo in the confguration file $ conf ['vjs_mediainfo_dir'] = '/ usr / bin /';
// $ conf ['vjs_exiftool_dir'] = '/ usr / bin /';
$ conf ['vjs_ffprobe_dir'] = '/ usr / bin /';
$ conf ['ffmpeg_dir'] = '/ usr / bin /'; 

error:
![image](https://user-images.githubusercontent.com/85041576/120087369-89fd7680-c0e7-11eb-8cf2-4325267de8a3.png)


Could it be due to the fact that the video-js plugin (master version) sends the command to ffmpeg with the abbreviated Path (./galleries/newvideo/pwg_representative/SampleVideo.jpg)?

Thanks for support
Grazie!
